networks:
  cafe-network-dev:
    driver: bridge

services:
  api:
    build: 
      context: ./backend
      target: development
    container_name: cafe-mapper-api-dev
    restart: unless-stopped
    networks:
      - cafe-network-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # Live code reloading
      - ./data:/app/data
      - ./backend/app/static/results:/app/app/static/results
    environment:
      - ENV=development
      - DATA_DIR=/app/data
      - OUTPUTS_DIR=/app/data/outputs
      - STATIC_RESULTS=/app/app/static/results
      - PYTHONPATH=/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build: 
      context: ./frontend
      target: development
    container_name: cafe-mapper-web-dev
    restart: unless-stopped
    networks:
      - cafe-network-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Live code reloading
      - /app/node_modules  # Exclude node_modules from volume mount
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      api:
        condition: service_healthy