version: "3.8"
services:
  api:
    build: ./backend
    container_name: cafe-mapper-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./data:/app/data
    environment:
      - ENV=dev

  web:
    build: ./frontend
    container_name: cafe-mapper-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - api
