networks:
  cafe-network:
    driver: bridge

volumes:
  cafe-data:
    driver: local
  cafe-results:
    driver: local

services:
  api:
    build: 
      context: ./backend
      target: production
    container_name: cafe-mapper-api
    restart: unless-stopped
    networks:
      - cafe-network
    ports:
      - "8000:8000"
    volumes:
      - cafe-data:/app/data
      - cafe-results:/app/app/static/results
      - ./backend/app:/app/app:ro  # Read-only code mount for development
      - ./backend/models:/app/models  # ML models directory
      - ./backend/ml_system:/app/ml_system  # ML system directory
    environment:
      - ENV=production
      - DATA_DIR=/app/data
      - OUTPUTS_DIR=/app/data/outputs
      - STATIC_RESULTS=/app/app/static/results
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  web:
    build: 
      context: ./frontend
      target: production
    container_name: cafe-mapper-web
    restart: unless-stopped
    networks:
      - cafe-network
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Optional: Redis for caching (future enhancement)
  # redis:
  #   image: redis:alpine
  #   container_name: cafe-mapper-redis
  #   restart: unless-stopped
  #   networks:
  #     - cafe-network
  #   volumes:
  #     - redis-data:/data
  #   command: redis-server --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
